// @ts-nocheck -- skip type checking
import * as docs_5 from "../content/docs/introduction/slash-commands/achievements.mdx?collection=docs&hash=1747484992759"
import * as docs_4 from "../content/docs/introduction/tos.mdx?collection=docs&hash=1747484992759"
import * as docs_3 from "../content/docs/introduction/index.mdx?collection=docs&hash=1747484992759"
import * as docs_2 from "../content/docs/introduction/hello.mdx?collection=docs&hash=1747484992759"
import * as docs_1 from "../content/docs/introduction/faq.mdx?collection=docs&hash=1747484992759"
import * as docs_0 from "../content/docs/introduction/aliases.mdx?collection=docs&hash=1747484992759"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"introduction/aliases.mdx","absolutePath":"/Users/loeungsopheak/Documents/GitHub/pompoki.tcg/content/docs/introduction/aliases.mdx"}, data: docs_0 }, { info: {"path":"introduction/faq.mdx","absolutePath":"/Users/loeungsopheak/Documents/GitHub/pompoki.tcg/content/docs/introduction/faq.mdx"}, data: docs_1 }, { info: {"path":"introduction/hello.mdx","absolutePath":"/Users/loeungsopheak/Documents/GitHub/pompoki.tcg/content/docs/introduction/hello.mdx"}, data: docs_2 }, { info: {"path":"introduction/index.mdx","absolutePath":"/Users/loeungsopheak/Documents/GitHub/pompoki.tcg/content/docs/introduction/index.mdx"}, data: docs_3 }, { info: {"path":"introduction/tos.mdx","absolutePath":"/Users/loeungsopheak/Documents/GitHub/pompoki.tcg/content/docs/introduction/tos.mdx"}, data: docs_4 }, { info: {"path":"introduction/slash-commands/achievements.mdx","absolutePath":"/Users/loeungsopheak/Documents/GitHub/pompoki.tcg/content/docs/introduction/slash-commands/achievements.mdx"}, data: docs_5 }], [{"info":{"path":"meta.json","absolutePath":"/Users/loeungsopheak/Documents/GitHub/pompoki.tcg/content/docs/meta.json"},"data":{"pages":["introduction"],"icon":"home"}}, {"info":{"path":"introduction/meta.json","absolutePath":"/Users/loeungsopheak/Documents/GitHub/pompoki.tcg/content/docs/introduction/meta.json"},"data":{"title":"Documentation","pages":["---Introduction---","index","tos","faq","---Other---","aliases","slash-commands"],"description":"Beta Pre-Release","root":true,"icon":"home"}}])